name: format_indonesia_v2
description: Library for Indonesian date and numeric formatting, it helps to reformat date and numeric variable to Indonesia language
version: 0.0.4
repository: https://github.com/rizkyghofur/format_indonesia_v2

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  test: ^1.25.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
