name: format_indonesia_v2
description: Library for Indonesian date and numeric formatting, it helps to reformat date and numeric variable to Indonesia language
version: 0.0.8
repository: https://github.com/rizkyghofur/format_indonesia_v2

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  intl: ^0.20.2
  test: ^1.25.2
